### ISSUE TITLE
issue in calculate_indel.py

### ISSUE THREAD

**Issue by milw** [fengzhanglab/Screening_Protocols_manuscript#1]
I'm getting this error:
Traceback (most recent call last):
  File "calculate_indel.py", line 399, in <module>
    args.input_name, args.hash, args.verbose, args.quiet)
  File "calculate_indel.py", line 345, in single_entry_read
    sample, total_list_string, indel_rate, note))
NameError: global name 'sample' is not defined

Is this a potential version issue with the other required python modules?

**Comment by jgoot** [comment]
Hi Scott,

This was actually an issue on our end -- it should be corrected now.

Thanks!

**Comment by milw** [comment]
Hi Jonathon, thanks for the quick update! I got it to run, hopefully the output will make sense.
cheers- Scott
